export enum ROLE {
  MEMBER = "MEMBER",
  ADMIN = "ADMIN",
}

export enum STATUS {
  BLOCKED = "BLOCKED",
  NOT_VERIFIED = "NOT_VERIFIED",
  VERIFIED = "VERIFIED",
  WITHOUT_PAYMENT = "WITHOUT_PAYMENT",
  WITHOUT_SUBSCRIBE = "WITHOUT_SUBSCRIBE",
  WITH_PAYMENT = "WITH_PAYMENT",
}
